// Generated by Wrangler by running `wrangler types`

interface Env {
	FIREBASE_PROJECT_ID: "vetbookexe";
	VAPID_PUBLIC_KEY: "BPJ7Kp1XlL6y1n6yvg4dbj24-mtBq4ThlNJsSA9X92K7xdHlooU4LPJa35Ff9rhq4sDRDlLNC4WGbp-WnYg21Fg";
	VAPID_MAILTO: "mailto:admin@vetbook.app";
}
